package org.goko.autoleveler.bean;

import org.goko.core.common.exception.GkException;

public interface IHeightMapBuilder {

	/**
	 * Returns the offset map generated by this builder
	 * @return an IOffsetMap
	 * @throws GkException GkException
	 */
	IHeightMap getMap() throws GkException;

}
